[package]
name = "bootstore"
description = "Storage required for rack unlock"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[build-dependencies.omicron-rpaths]
path = "../rpaths"

[dependencies]
bcs = "0.1.3"
derive_more = "0.99.17"
diesel = { version = "2.0.0-rc.1", features = ["sqlite", "uuid"] }
p256 = "0.9.0"
# See omicron-rpaths for more about the "pq-sys" dependency.
# We don't actually need `pq-sys` here, other than to satisfy
# `[build-dependencies.omicron-rpaths]`, which are needed by `omicron-test-
# utils`. Unfortunately, it doesn't appear possible to put the `pq-sys` dep
# only in `[dev-dependencies]`.
pq-sys = "*"
rand = { version = "0.8.5", features = ["getrandom"] }
serde = { version = "1.0", features = [ "derive" ] }
sha3 = "0.10.1"
slog = { version = "2.5", features = [ "max_level_trace", "release_max_level_debug" ] }
sprockets-common = { git = "http://github.com/oxidecomputer/sprockets", rev = "0361fd13ff19cda6696242fe40f1325fca30d3d1" }
sprockets-host = { git = "http://github.com/oxidecomputer/sprockets", rev = "0361fd13ff19cda6696242fe40f1325fca30d3d1" }
thiserror = "1.0"
uuid = { version = "1.1.0", features = [ "serde", "v4" ] }
vsss-rs = { version = "2.0.0", default-features = false, features = ["std"] }

[dev-dependencies]
assert_matches = "1.5.0"
bincode = "1.3.3"
omicron-test-utils = { path = "../test-utils" }
