[package]
name = "internal-dns-cli"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
dropshot.workspace = true
hickory-resolver.workspace = true
internal-dns-resolver.workspace = true
internal-dns-types.workspace = true
omicron-common.workspace = true
oxide-tokio-rt.workspace = true
slog.workspace = true
tokio.workspace = true
omicron-workspace-hack.workspace = true
