[package]
name = "gfss"
version = "0.1.0"
description = "Shamir secret sharing over GF(2^8)"
edition = "2024"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
digest.workspace = true
rand = { workspace = true, features = ["getrandom"] }
secrecy.workspace = true
serde.workspace = true
subtle = "2.6"
thiserror.workspace = true
zeroize.workspace = true
omicron-workspace-hack.workspace = true

[dev-dependencies]
proptest.workspace = true
test-strategy.workspace = true
