[package]
name = "gfss"
version = "0.1.0"
description = "Shamir secret sharing over GF(2^8)"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
digest.workspace = true
rand09.workspace = true
secrecy.workspace = true
serde.workspace = true
subtle.workspace = true
thiserror.workspace = true
zeroize.workspace = true
omicron-workspace-hack.workspace = true

[dev-dependencies]
proptest.workspace = true
test-strategy.workspace = true
