[package]
name = "internal-dns-cli"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow.workspace = true
clap.workspace = true
dropshot.workspace = true
internal-dns.workspace = true
omicron-common.workspace = true
slog.workspace = true
tokio.workspace = true
hickory-resolver.workspace = true
omicron-workspace-hack.workspace = true
