[package]
name = "gateway-types"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
gateway-types-versions.workspace = true
omicron-workspace-hack.workspace = true

[features]
testing = ["gateway-types-versions/testing"]
