[package]
name = "sled-agent-types"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
bootstore.workspace = true
camino.workspace = true
chrono.workspace = true
daft.workspace = true
iddqd.workspace = true
nexus-sled-agent-shared.workspace = true
# Note: we're trying to avoid a dependency from sled-agent-types to nexus-types
# because the correct direction of dependency is unclear. If there are types
# common to both, put them in `omicron-common` or `nexus-sled-agent-shared`.
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
omicron-workspace-hack.workspace = true
oxnet.workspace = true
propolis-client.workspace = true
schemars.workspace = true
serde.workspace = true
serde_human_bytes.workspace = true
serde_json.workspace = true
sha3.workspace = true
sled-hardware-types.workspace = true
slog.workspace = true
slog-error-chain.workspace = true
strum.workspace = true
swrite.workspace = true
thiserror.workspace = true
toml.workspace = true
tufaceous-artifact.workspace = true
uuid.workspace = true

[dev-dependencies]
camino-tempfile.workspace = true
omicron-test-utils.workspace = true
rcgen.workspace = true
