[package]
name = "installinator-client"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
oxide-update-engine-types.workspace = true
progenitor.workspace = true
regress.workspace = true
reqwest = { workspace = true, features = ["rustls", "stream"] }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
slog.workspace = true
omicron-workspace-hack.workspace = true
