[package]
name = "installinator-client"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
progenitor.workspace = true
regress.workspace = true
reqwest = { workspace = true, features = ["rustls-tls", "stream"] }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
slog.workspace = true
update-engine.workspace = true
omicron-workspace-hack.workspace = true
