[package]
name = "nexus-reconfigurator-planning"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clickhouse-admin-types.workspace = true
chrono.workspace = true
debug-ignore.workspace = true
daft.workspace = true
gateway-client.workspace = true
gateway-types.workspace = true
id-map.workspace = true
illumos-utils.workspace = true
indexmap.workspace = true
internal-dns-resolver.workspace = true
ipnet.workspace = true
itertools.workspace = true
nexus-config.workspace = true
nexus-inventory.workspace = true
nexus-reconfigurator-blippy.workspace = true
nexus-sled-agent-shared.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
once_cell.workspace = true
oxnet.workspace = true
rand.workspace = true
semver.workspace = true
sled-agent-client.workspace = true
slog.workspace = true
slog-error-chain.workspace = true
sp-sim.workspace = true
static_assertions.workspace = true
strum.workspace = true
thiserror.workspace = true
tufaceous-artifact.workspace = true
typed-rng.workspace = true
uuid.workspace = true

omicron-workspace-hack.workspace = true

[dev-dependencies]
dropshot.workspace = true
expectorate.workspace = true
maplit.workspace = true
omicron-common = { workspace = true, features = ["testing"] }
omicron-test-utils.workspace = true
proptest.workspace = true
semver.workspace = true
test-strategy.workspace = true
