[package]
name = "cockroach-admin-types"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
cockroach-admin-types-versions.workspace = true
omicron-workspace-hack.workspace = true
serde.workspace = true
