[toolchain]
# We choose a specific toolchain (rather than "stable") for repeatability.  The
# intent is to keep this up-to-date with recently-released stable Rust.

channel = "1.87.0"
profile = "default"
