[package]
name = "omicron-deploy"
description = "Tools for deploying Omicron software to target machines"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
crossbeam.workspace = true
omicron-package.workspace = true
serde.workspace = true
serde_derive.workspace = true
thiserror.workspace = true
omicron-workspace-hack.workspace = true

[[bin]]
name = "thing-flinger"
doc = false
