#
# Oxide API: example configuration file
#

# Identifier for this instance of Nexus
id = "e6bff1ff-24fb-49dc-a54e-c6a350cd4d6c"

[console]
# Directory for static assets. Absolute path or relative to CWD.
static_dir = "/var/nexus/static"
cache_control_max_age_minutes = 10
session_idle_timeout_minutes = 60
session_absolute_timeout_minutes = 480

[authn]
# TODO(https://github.com/oxidecomputer/omicron/issues/372): Remove "spoof".
schemes_external = ["spoof", "session_cookie"]

[database]
# URL for connecting to the database
url = "postgresql://root@[fd00:1122:3344:0101::2]:32221/omicron?sslmode=disable"

[dropshot_external]
# IP address and TCP port on which to listen for the external API
bind_address = "[fd00:1122:3344:0101::3]:12220"
request_body_max_bytes = 1048576

[dropshot_internal]
# IP address and TCP port on which to listen for the internal API
bind_address = "[fd00:1122:3344:0101::3]:12221"
request_body_max_bytes = 1048576

[log]
# Show log messages of this level and more severe
level = "info"
mode = "file"
path = "/dev/stdout"
if_exists = "append"

# Configuration for interacting with the timeseries database
[timeseries_db]
address = "[fd00:1122:3344:0101::5]:8123"
