#
# Oxide API: example configuration file
#

# Identifier for this instance of Nexus
id = "e6bff1ff-24fb-49dc-a54e-c6a350cd4d6c"

[console]
# Directory for static assets. Absolute path or relative to CWD.
static_dir = "nexus/static"
cache_control_max_age_minutes = 10
session_idle_timeout_minutes = 60
session_absolute_timeout_minutes = 480

[authn]
# TODO(https://github.com/oxidecomputer/omicron/issues/372): Remove "spoof".
schemes_external = ["spoof"]

[database]
# URL for connecting to the database
url = "postgresql://root@[fd00:1234::5]:32221/omicron?sslmode=disable"

[dropshot_external]
# IP address and TCP port on which to listen for the external API
bind_address = "192.168.1.123:12220"

[dropshot_internal]
# IP address and TCP port on which to listen for the internal API
bind_address = "[fd00:1234::7]:12221"

[log]
# Show log messages of this level and more severe
level = "info"

# Example output to a terminal (with colors)
mode = "stderr-terminal"

# Example output to a file, appending if it already exists.
#mode = "file"
#path = "logs/server.log"
#if_exists = "append"

# Configuration for interacting with the timeseries database
[timeseries_db]
address = "[fd00:1234::8]:8123"
