[package]
name = "update-common"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
camino.workspace = true
camino-tempfile.workspace = true
chrono.workspace = true
debug-ignore.workspace = true
display-error-chain.workspace = true
dropshot.workspace = true
futures.workspace = true
hex.workspace = true
hubtools.workspace = true
omicron-common.workspace = true
sha2.workspace = true
slog.workspace = true
thiserror.workspace = true
tokio.workspace = true
tokio-util.workspace = true
tough.workspace = true
tufaceous-lib.workspace = true
omicron-workspace-hack.workspace = true

[dev-dependencies]
clap.workspace = true
omicron-test-utils.workspace = true
rand.workspace = true
tufaceous.workspace = true
