[package]
name = "oximeter-test-utils"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clickward.workspace = true
omicron-workspace-hack.workspace = true
omicron-test-utils.workspace = true
oximeter-db.workspace = true
oximeter-macro-impl.workspace = true
oximeter-types.workspace = true
slog.workspace =true
uuid.workspace = true
