[package]
name = "sled-hardware"
description = "Monitoring and managing sled-local hardware"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
cfg-if.workspace = true
futures.workspace = true
gethostname.workspace = true
illumos-utils.workspace = true
libc.workspace = true
macaddr.workspace = true
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
rand.workspace = true
schemars.workspace = true
serde.workspace = true
sled-hardware-types.workspace = true
slog.workspace = true
slog-error-chain.workspace = true
thiserror.workspace = true
tofino.workspace = true
tokio.workspace = true
uuid.workspace = true
omicron-workspace-hack.workspace = true

[target.'cfg(target_os = "illumos")'.dependencies]
illumos-devinfo = { git = "https://github.com/oxidecomputer/illumos-devinfo", branch = "main" }
libefi-illumos = { git = "https://github.com/oxidecomputer/libefi-illumos", branch = "master" }
libnvme.workspace = true

[dev-dependencies]
illumos-utils = { workspace = true, features = ["testing"] }
omicron-test-utils.workspace = true

[features]
testing = []
