[package]
name = "omicron-live-tests"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[build-dependencies]
omicron-rpaths.workspace = true

[dependencies]
# See omicron-rpaths for more about the "pq-sys" dependency.
pq-sys = "*"
omicron-workspace-hack.workspace = true

[dev-dependencies]
anyhow.workspace = true
assert_matches.workspace = true
dns-service-client.workspace = true
dropshot.workspace = true
futures.workspace = true
internal-dns-resolver.workspace = true
internal-dns-types.workspace = true
live-tests-macros.workspace = true
nexus-config.workspace = true
nexus-db-model.workspace = true
nexus-db-queries.workspace = true
nexus-inventory.workspace = true
nexus-lockstep-client.workspace = true
nexus-reconfigurator-planning.workspace = true
nexus-reconfigurator-preparation.workspace = true
sled-agent-types-migrations.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
omicron-test-utils.workspace = true
omicron-uuid-kinds.workspace = true
reqwest.workspace = true
serde.workspace = true
slog.workspace = true
slog-error-chain.workspace = true
textwrap.workspace = true
tokio.workspace = true
uuid.workspace = true

[lints]
workspace = true
