[package]
name = "cockroach-admin-api"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
cockroach-admin-types-versions.workspace = true
dropshot.workspace = true
dropshot-api-manager-types.workspace = true
http.workspace = true
omicron-common.workspace = true
omicron-workspace-hack.workspace = true
semver.workspace = true
