[package]
name = "oximeter"
version = "0.1.0"
authors = ["Benjamin Naecker <ben@oxide.computer>"]
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
clap.workspace = true
chrono.workspace = true
omicron-workspace-hack.workspace = true
oximeter-macro-impl.workspace = true
oximeter-schema.workspace = true
oximeter-timeseries-macro.workspace = true
oximeter-types.workspace = true
prettyplease.workspace = true
syn.workspace = true
toml.workspace = true
uuid.workspace = true
