[package]
name = "oximeter"
version = "0.1.0"
authors = ["Benjamin Naecker <ben@oxide.computer>"]
edition = "2018"

[dependencies]
bytes = { version = "1.0.1", features = [ "serde" ] }
chrono = { version = "0.4.19", features = [ "serde" ] }
num-traits = "0.2.14"
omicron-common = { path = "../../common" }
oximeter-macro-impl = { path = "../oximeter-macro-impl" }
reqwest = { version = "0.11.6", features = [ "json" ] }
schemars = { version = "0.8.6", features = [ "uuid", "bytes", "chrono" ] }
serde = { version = "1", features = [ "derive" ] }
slog = { version = "2.5", features = [ "max_level_trace", "release_max_level_debug" ] }
thiserror = "1.0.30"
uuid = { version = "0.8.2", features = [ "v4", "serde" ] }

[dev-dependencies]
trybuild = "1.0.49"
omicron-test-utils = { path = "../../test-utils" }
