[package]
name = "oximeter"
version = "0.1.0"
authors = ["Benjamin Naecker <ben@oxide.computer>"]
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
bytes = { workspace = true, features = [ "serde" ] }
chrono.workspace = true
num.workspace = true
omicron-common.workspace = true
oximeter-macro-impl.workspace = true
regex.workspace = true
schemars = { workspace = true, features = [ "uuid1", "bytes", "chrono" ] }
serde.workspace = true
serde_json.workspace = true
strum.workspace = true
thiserror.workspace = true
uuid.workspace = true
omicron-workspace-hack.workspace = true

[dev-dependencies]
approx.workspace = true
rstest.workspace = true
serde_json.workspace = true
trybuild.workspace = true
