[package]
name = "oximeter"
version = "0.1.0"
authors = ["Benjamin Naecker <ben@oxide.computer>"]
edition = "2021"
license = "MPL-2.0"

[dependencies]
bytes = { workspace = true, features = [ "serde" ] }
chrono.workspace = true
num-traits.workspace = true
oximeter-macro-impl.workspace = true
schemars = { workspace = true, features = [ "uuid1", "bytes", "chrono" ] }
serde.workspace = true
thiserror.workspace = true
uuid.workspace = true

[dev-dependencies]
trybuild.workspace = true
