[package]
name = "oximeter"
version = "0.1.0"
authors = ["Benjamin Naecker <ben@oxide.computer>"]
edition = "2018"

[dependencies]
bytes = { version = "1.0.1", features = [ "serde" ] }
chrono = { version = "0.4.19", features = [ "serde" ] }
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main" }
num-traits = "0.2.14"
hyper = "0.14.7"
oximeter-macro-impl = { path = "../oximeter-macro-impl" }
omicron-common = { path = "../../omicron-common" }
reqwest = { version = "0.11.3", features = [ "json" ] }
schemars = { version = "0.8.3", features = [ "uuid", "bytes", "chrono" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1.0.0"
slog = { version = "2.5", features = [ "max_level_trace", "release_max_level_debug" ] }
structopt = "0.3"
thiserror = "1.0.24"
tokio = "1.6"
uuid = { version = "0.8.2", features = [ "v4", "serde" ] }
