[package]
name = "oximeter"
version = "0.1.0"
authors = ["Benjamin Naecker <ben@oxide.computer>"]
edition = "2018"

[dependencies]
anyhow = "1.0"
bytes = { version = "1.0.1", features = [ "serde" ] }
chrono = { version = "0.4.19", features = [ "serde" ] }
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main" }
num-traits = "0.2.14"
hyper = "0.14.13"
oximeter-macro-impl = { path = "../oximeter-macro-impl" }
omicron-common = { path = "../../omicron-common" }
reqwest = { version = "0.11.4", features = [ "json" ] }
schemars = { version = "0.8.6", features = [ "uuid", "bytes", "chrono" ] }
serde = { version = "1", features = [ "derive" ] }
serde_json = "1.0.68"
slog = { version = "2.5", features = [ "max_level_trace", "release_max_level_debug" ] }
slog-async = "2.6"
slog-term = "2.8"
structopt = "0.3"
thiserror = "1.0.26"
tokio = "1.12"
toml = "0.5.8"
uuid = { version = "0.8.2", features = [ "v4", "serde" ] }

[dev-dependencies]
trybuild = "1.0.44"
omicron-test-utils = { path = "../../test-utils" }

[[bin]]
name = "oxdb"
doc = false
