[package]
name = "nexus-inventory"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
camino.workspace = true
chrono.workspace = true
clickhouse-admin-keeper-client.workspace = true
dns-service-client.workspace = true
clickhouse-admin-server-client.workspace = true
clickhouse-admin-types.workspace = true
cockroach-admin-types.workspace = true
futures.workspace = true
gateway-client.workspace = true
gateway-messages.workspace = true
gateway-types.workspace = true
iddqd.workspace = true
itertools.workspace = true
sled-agent-types-migrations.workspace = true
nexus-types.workspace = true
ntp-admin-client.workspace = true
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
reqwest.workspace = true
serde_json.workspace = true
sled-agent-client.workspace = true
sled-agent-types.workspace = true
sled-agent-zone-images-examples.workspace = true
slog.workspace = true
slog-error-chain.workspace = true
strum.workspace = true
swrite.workspace = true
thiserror.workspace = true
tufaceous-artifact.workspace = true
typed-rng.workspace = true
uuid.workspace = true
omicron-cockroach-metrics.workspace = true
omicron-workspace-hack.workspace = true

[dev-dependencies]
expectorate.workspace = true
gateway-test-utils.workspace = true
httpmock.workspace = true
nexus-client.workspace = true
omicron-sled-agent.workspace = true
regex.workspace = true
tokio.workspace = true
