[package]
name = "nexus-inventory"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
base64.workspace = true
chrono.workspace = true
clickhouse-admin-keeper-client.workspace = true
clickhouse-admin-server-client.workspace = true
clickhouse-admin-types.workspace = true
futures.workspace = true
gateway-client.workspace = true
gateway-messages.workspace = true
gateway-types.workspace = true
id-map.workspace = true
nexus-sled-agent-shared.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
reqwest.workspace = true
serde_json.workspace = true
sled-agent-client.workspace = true
slog.workspace = true
strum.workspace = true
thiserror.workspace = true
typed-rng.workspace = true
uuid.workspace = true
omicron-workspace-hack.workspace = true

[dev-dependencies]
expectorate.workspace = true
gateway-test-utils.workspace = true
omicron-sled-agent.workspace = true
regex.workspace = true
tokio.workspace = true
