[package]
name = "sled-agent-api"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
camino.workspace = true
chrono.workspace = true
dropshot.workspace = true
dropshot-api-manager-types.workspace = true
http.workspace = true
iddqd.workspace = true
nexus-sled-agent-shared.workspace = true
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
omicron-workspace-hack.workspace = true
schemars.workspace = true
semver.workspace = true
serde.workspace = true
sled-agent-types.workspace = true
sled-diagnostics.workspace = true
sled-hardware-types.workspace = true
tufaceous-artifact.workspace = true
uuid.workspace = true
