[package]
name = "omicron-dev-lib"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
libc.workspace = true
omicron-test-utils.workspace = true
omicron-workspace-hack.workspace = true
subprocess.workspace = true
