[package]
name = "omicron-ls-apis"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
cargo_metadata.workspace = true
clap.workspace = true
iddqd.workspace = true
indent_write.workspace = true
newtype_derive.workspace = true
parse-display.workspace = true
petgraph.workspace = true
serde.workspace = true
toml.workspace = true
omicron-workspace-hack.workspace = true

[dev-dependencies]
expectorate.workspace = true
omicron-test-utils.workspace = true
subprocess.workspace = true
