[package]
name = "update-engine"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow.workspace = true
debug-ignore.workspace = true
derive-where.workspace = true
futures.workspace = true
linear-map.workspace = true
petgraph.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
schemars.workspace = true
slog.workspace = true
tokio = { workspace = true, features = ["macros", "sync", "time", "rt-multi-thread"] }
uuid.workspace = true

[dev-dependencies]
buf-list.workspace = true
bytes.workspace = true
camino.workspace = true
indexmap.workspace = true
indicatif.workspace = true
omicron-test-utils.workspace = true
owo-colors.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["io-util"] }
tokio-stream.workspace = true
