# Example configuration file for running an oximeter collector server

id = "1da65e5b-210c-4859-a7d7-200c1e659972"
nexus_address = "127.0.0.1:12221"
cache_dir = "/tmp"

[db]
address = "[::1]:8123"
batch_size = 1000
batch_interval = 5 # In seconds

[log]
level = "debug"
mode = "stderr-terminal"

[dropshot]
bind_address = "[::1]:12223"
