[package]
name = "sled-agent-measurements"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
bytes.workspace = true
camino.workspace = true
key-manager.workspace = true
sled-agent-types.workspace = true
sled-agent-types-versions.workspace = true
sled-agent-config-reconciler.workspace = true
sled-agent-resolvable-files.workspace = true
serde.workspace = true
slog.workspace = true
slog-error-chain.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }

omicron-workspace-hack.workspace = true

[dev-dependencies]

[features]
testing = []
