[package]
name = "omicron-measurement-diagnose"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[build-dependencies]
omicron-rpaths.workspace = true
vergen-gitcl.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
attest-data.workspace = true
camino.workspace = true
clap.workspace = true
dice-verifier.workspace = true
der.workspace = true
dropshot.workspace = true
futures.workspace = true
omicron-workspace-hack.workspace = true
oxide-tokio-rt.workspace = true
pem.workspace = true
# See omicron-rpaths for more about the "pq-sys" dependency.
pq-sys = "*"
rats-corim.workspace = true
reqwest.workspace = true
serde.workspace = true
serde_json.workspace = true
sled-agent-client.workspace = true
sled-agent-types.workspace = true
slog.workspace = true
slog-error-chain.workspace = true
strum.workspace = true
tokio = { workspace = true, features = ["full"] }
tufaceous-artifact.workspace = true

[dev-dependencies]

# Disable doc builds by default for our binaries to work around issue
# rust-lang/cargo#8373.  These docs would not be very useful anyway.
[[bin]]
name = "measurement-diagnose"
doc = false
