[package]
name = "sp-sim"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.51"
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main", features = [ "usdt-probes" ] }
gateway-messages = { path = "../gateway-messages" }
hex = "0.4.3"
omicron-common = { path = "../common" }
slog-dtrace = "0.2"
structopt = "0.3"
thiserror = "1.0"
toml = "0.5.6"

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.slog]
version = "2.7"
features = [ "max_level_trace", "release_max_level_debug" ]

[dependencies.tokio]
version = "1.16"
features = [ "full" ]

[[bin]]
name = "sp-sim"
