[package]
name = "sp-sim"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.53"
clap = { version = "3.2", features = ["derive"] }
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main", features = [ "usdt-probes" ] }
futures = "0.3"
gateway-messages = { path = "../gateway-messages", default-features = false, features = ["std"] }
hex = { version = "0.4.3", features = ["serde"] }
omicron-common = { path = "../common" }
slog-dtrace = "0.2"
sprockets-rot = { git = "http://github.com/oxidecomputer/sprockets", rev = "0361fd13ff19cda6696242fe40f1325fca30d3d1" }
thiserror = "1.0"
toml = "0.5.9"

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.slog]
version = "2.7"
features = [ "max_level_trace", "release_max_level_debug" ]

[dependencies.tokio]
version = "1.18"
features = [ "full" ]

[[bin]]
name = "sp-sim"
