[package]
name = "sp-sim"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
dropshot.workspace = true
ecdsa.workspace = true
futures.workspace = true
gateway-ereport-messages.workspace = true
gateway-messages.workspace = true
gateway-types.workspace = true
hex = { workspace = true, features = [ "serde" ] }
hubtools.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
oxide-tokio-rt.workspace = true
p256.workspace = true
rand.workspace = true
ssh-key.workspace = true
serde.workspace = true
serde_cbor.workspace = true
sha2.workspace = true
sha3.workspace = true
slog.workspace = true
slog-dtrace.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [ "full" ] }
toml.workspace = true
omicron-workspace-hack.workspace = true
nix.workspace = true
uuid.workspace = true
zerocopy.workspace = true

[[bin]]
name = "sp-sim"
