[package]
name = "sp-sim"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.58"
clap = { version = "4.0", features = ["derive"] }
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main", features = [ "usdt-probes" ] }
futures = "0.3"
hex = { version = "0.4.3", features = ["serde"] }
omicron-common = { path = "../common" }
slog-dtrace = "0.2"
sprockets-rot = { git = "http://github.com/oxidecomputer/sprockets", rev = "77df31efa5619d0767ffc837ef7468101608aee9" }
thiserror = "1.0"
toml = "0.5.9"

[dependencies.gateway-messages]
git = "https://github.com/oxidecomputer/management-gateway-service"
rev = "c1484109c394f45e08018e0f35adc4a136cd207d"
default-features = false
features = ["std"]

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.slog]
version = "2.7"
features = [ "max_level_trace", "release_max_level_debug" ]

[dependencies.tokio]
version = "1.21"
features = [ "full" ]

[[bin]]
name = "sp-sim"
