[package]
name = "sp-sim"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
clap.workspace = true
dropshot.workspace = true
futures.workspace = true
omicron-gateway.workspace = true
gateway-messages.workspace = true
hex = { workspace = true, features = [ "serde" ] }
omicron-common.workspace = true
serde.workspace = true
slog.workspace = true
slog-dtrace.workspace = true
sprockets-rot.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = [ "full" ] }
toml.workspace = true
omicron-workspace-hack.workspace = true

[[bin]]
name = "sp-sim"
