[package]
name = "internal-dns-types"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
omicron-common.workspace = true
omicron-workspace-hack.workspace = true
omicron-uuid-kinds.workspace = true
schemars.workspace = true
serde.workspace = true

[dev-dependencies]
expectorate.workspace = true
serde_json.workspace = true
