[package]
name = "clickhouse-admin-api"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
clickhouse-admin-types.workspace = true
dropshot.workspace = true
dropshot-api-manager-types.workspace = true
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
omicron-workspace-hack.workspace = true
schemars.workspace = true
semver.workspace = true
serde.workspace = true
