[package]
name = "omicron-test-utils"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
atomicwrites.workspace = true
camino.workspace = true
camino-tempfile.workspace = true
dropshot.workspace = true
filetime = { workspace = true, optional = true }
futures.workspace = true
headers.workspace = true
hex.workspace = true
http.workspace = true
libc.workspace = true
nexus-config.workspace = true
omicron-common.workspace = true
oxide-tokio-rt.workspace = true
pem.workspace = true
regex.workspace = true
ring.workspace = true
rustls.workspace = true
slog.workspace = true
subprocess.workspace = true
tempfile.workspace = true
thiserror.workspace = true
tar.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-postgres.workspace = true
usdt.workspace = true
rcgen.workspace = true
reqwest.workspace = true
walkdir.workspace = true
omicron-workspace-hack.workspace = true
uuid.workspace = true

[dev-dependencies]
chrono.workspace = true
expectorate.workspace = true
gethostname.workspace = true
serde.workspace = true

[features]
seed-gen = ["dep:filetime"]

[target.'cfg(target_os = "illumos")'.dependencies]
libfalcon.workspace = true

[[bin]]
name = "falcon_runner"

[[bin]]
name = "falcon_runner_cli"
