[package]
name = "nexus-config"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
dropshot.workspace = true
ipnet.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
omicron-workspace-hack.workspace = true
schemars.workspace = true
serde.workspace = true
serde_with.workspace = true
tokio-postgres.workspace = true
toml.workspace = true
uuid.workspace = true

[dev-dependencies]
expectorate.workspace = true
libc.workspace = true
serde_json.workspace = true
pretty_assertions.workspace = true
