[package]
name = "omicron-releng"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow.workspace = true
camino.workspace = true
camino-tempfile.workspace = true
cargo_metadata.workspace = true
chrono.workspace = true
clap.workspace = true
fs-err = { workspace = true, features = ["tokio"] }
futures.workspace = true
hex.workspace = true
omicron-common.workspace = true
omicron-workspace-hack.workspace = true
omicron-zone-package.workspace = true
once_cell.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
sha2.workspace = true
shared-client.workspace = true
shell-words.workspace = true
slog.workspace = true
slog-async.workspace = true
slog-term.workspace = true
tar.workspace = true
tokio = { workspace = true, features = ["full"] }
toml.workspace = true
tufaceous-lib.workspace = true

[lints]
workspace = true
