[package]
name = "omicron-releng"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[dependencies]
anyhow.workspace = true
camino.workspace = true
camino-tempfile.workspace = true
cargo_metadata.workspace = true
chrono.workspace = true
clap.workspace = true
fs-err = { workspace = true, features = ["tokio"] }
futures.workspace = true
hex.workspace = true
omicron-pins.workspace = true
omicron-workspace-hack.workspace = true
omicron-zone-package.workspace = true
rats-corim.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha2.workspace = true
shell-words.workspace = true
slog.workspace = true
slog-async.workspace = true
slog-term.workspace = true
tar.workspace = true
tokio = { workspace = true, features = ["full"] }
toml.workspace = true
tufaceous.workspace = true
tufaceous-artifact-v1 = { git = "https://github.com/oxidecomputer/tufaceous", branch = "main", package = "tufaceous-artifact" }
tufaceous-lib-v1 = { git = "https://github.com/oxidecomputer/tufaceous", branch = "main", package = "tufaceous-lib" }
update-common.workspace = true

[lints]
workspace = true
