[package]
name = "oximeter-timeseries-macro"
version = "0.1.0"
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
omicron-workspace-hack.workspace = true
oximeter-schema.workspace = true
oximeter-types.workspace = true
proc-macro2.workspace = true
quote.workspace = true
syn.workspace = true

[lints]
workspace = true
