[package]
name = "clickhouse-admin-single-client"
version = "0.1.0"
edition.workspace = true

[dependencies]
chrono.workspace = true
clickhouse-admin-types.workspace = true
omicron-uuid-kinds.workspace = true
progenitor.workspace = true
reqwest = { workspace = true, features = [ "json", "rustls-tls", "stream" ] }
schemars.workspace = true
serde.workspace = true
slog.workspace = true
omicron-workspace-hack.workspace = true

[lints]
workspace = true
