[dropshot]
# 100 MiB.  This ought to be large enough for a while, but not so large that
# we'll use tons of memory parsing it.
request_body_max_bytes = 104857600

[log]
# Show log messages of this level and more severe
level = "debug"
mode = "file"
path = "/dev/stdout"
if_exists = "append"

[storage]
storage_path = "/data/dns"
keep_old_generations = 3
