# Configuration for propolis server.
#
# Refer to https://github.com/oxidecomputer/propolis#readme
# for more detail on the config format.

bootrom = "/opt/oxide/propolis-server/blob/OVMF_CODE.fd"

[dev.block0]
driver = "pci-virtio-block"
disk = "/opt/oxide/propolis-server/blob/alpine.iso"
pci-path = "0.4.0"
