[package]
name = "db-macros"
version = "0.1.0"
authors = ["Sean Klein <sean@oxide.computer>"]
edition = "2021"
license = "MPL-2.0"

[lib]
proc-macro = true

[dependencies]
heck.workspace = true
proc-macro2.workspace = true
quote.workspace = true
serde.workspace = true
serde_tokenstream.workspace = true
syn.workspace = true

[dev-dependencies]
rustfmt-wrapper = "0.2"
