[package]
name = "nexus-defaults"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
ipnetwork.workspace = true
oxnet.workspace = true
rand.workspace = true
serde_json.workspace = true

omicron-common.workspace = true
omicron-workspace-hack.workspace = true
