[package]
name = "ereport-types"
version = "0.1.0"
edition.workspace = true

[dependencies]
dropshot.workspace = true
thiserror.workspace = true
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
omicron-workspace-hack.workspace = true
omicron-uuid-kinds.workspace = true

[lints]
workspace = true
