[package]
name = "ereporter-client"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
chrono.workspace = true
expectorate.workspace = true
ereport-types.workspace = true
http.workspace = true
progenitor.workspace = true
reqwest = { workspace = true, features = ["json", "rustls-tls", "stream"] }
schemars.workspace = true
serde.workspace = true
serde_json.workspace = true
slog.workspace = true
omicron-uuid-kinds.workspace = true
omicron-workspace-hack.workspace = true
uuid.workspace = true
