[package]
name = "db-macros"
version = "0.1.0"
authors = ["Sean Klein <sean@oxide.computer>"]
edition = "2021"
license = "MPL-2.0"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = { version = "1.0" }
quote = { version = "1.0" }
serde = { version = "1.0", features = [ "derive" ] }
serde_tokenstream = "0.1"
syn = { version = "1.0", features = [ "full", "derive", "extra-traits" ] }
