[package]
name = "nexus-saga-recovery"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[build-dependencies]
omicron-rpaths.workspace = true

[dependencies]
chrono.workspace = true
futures.workspace = true
nexus-db-queries.workspace = true
nexus-db-model.workspace = true
omicron-common.workspace = true
# See omicron-rpaths for more about the "pq-sys" dependency.
pq-sys = "*"
serde.workspace = true
serde_json.workspace = true
slog.workspace = true
slog-error-chain.workspace = true
steno.workspace = true
tokio.workspace = true

omicron-workspace-hack.workspace = true

[dev-dependencies]
nexus-auth.workspace = true
nexus-db-queries.workspace = true
nexus-test-utils.workspace = true
nexus-test-utils-macros.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
omicron-test-utils.workspace = true
pretty_assertions.workspace = true
steno.workspace = true
tokio.workspace = true
uuid.workspace = true
