[package]
name = "omicron-nexus"
version = "0.1.0"
edition = "2018"

[dependencies]
anyhow = "1.0"
async-trait = "0.1.50"
bb8 = "0.7.0"
bb8-postgres = "0.7.0"
futures = "0.3.15"
http = "0.2.0"
hyper = "0.14"
lazy_static = "1.4.0"
libc = "0.2.97"
newtype_derive = "0.1.6"
serde_json = "1.0"
serde_with = "1.9.4"
structopt = "0.3"
thiserror = "1.0"
toml = "0.5.6"

[dependencies.chrono]
version = "0.4"
features = [ "serde" ]

[dependencies.dropshot]
git = "https://github.com/oxidecomputer/dropshot"
branch = "main"

[dependencies.omicron-common]
path = "../omicron-common"

[dependencies.omicron-sled-agent]
path = "../omicron-sled-agent"

[dependencies.schemars]
version = "0.8"
features = [ "chrono", "uuid" ]

[dependencies.serde]
version = "1.0"
features = [ "derive" ]

[dependencies.slog]
version = "2.7"
features = [ "max_level_trace", "release_max_level_debug" ]

[dependencies.steno]
git = "https://github.com/oxidecomputer/steno"
branch = "main"

[dependencies.tokio]
version = "1.8"
features = [ "full" ]

[dependencies.tokio-postgres]
version = "0.7"
features = [ "with-chrono-0_4", "with-serde_json-1", "with-uuid-0_8" ]

[dependencies.uuid]
version = "0.8"
features = [ "serde", "v4" ]

[dev-dependencies]
bytes = "1.0.1"
expectorate = "1.0.1"
openapiv3 = "0.5.0"
subprocess = "0.2.7"

[dev-dependencies.oximeter]
version = "0.1.0"
path = "../oximeter/oximeter"

#
# Disable doc builds by default for our binaries to work around issue
# rust-lang/cargo#8373.  These docs would not be very useful anyway.
#
[[bin]]
name = "nexus"
doc = false
