[package]
name = "ereporter-api"
version = "0.1.0"
edition = "2024"

[dependencies]
ereport-types.workspace = true
dropshot.workspace = true
openapi-manager-types.workspace = true
schemars.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
uuid.workspace = true

[lints]
workspace = true
