[package]
name = "oximeter-api"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
dropshot.workspace = true
dropshot-api-manager-types.workspace = true
omicron-common.workspace = true
omicron-workspace-hack.workspace = true
oximeter-types-versions.workspace = true
semver.workspace = true
