# RSS (Rack Setup Service) "stand-in" configuration.

# The /56 subnet for the rack.
# Also implies the /48 AZ subnet.
#              |............|    <- This /48 is the AZ Subnet
#              |...............| <- This /56 is the Rack Subnet
rack_subnet = "fd00:1122:3344:0100::"

[[request]]

# TODO(https://github.com/oxidecomputer/omicron/issues/732): Nexus
# should allocate crucible datasets.
[[request.dataset]]
zpool_id = "d462a7f7-b628-40fe-80ff-4e4189e2d62b"
address = "[fd00:1122:3344:0101::6]:32345"
dataset_kind.type = "crucible"

[[request.dataset]]
zpool_id = "e4b4dc87-ab46-49fb-a4b4-d361ae214c03"
address = "[fd00:1122:3344:0101::7]:32345"
dataset_kind.type = "crucible"

[[request.dataset]]
zpool_id = "f4b4dc87-ab46-49fb-a4b4-d361ae214c03"
address = "[fd00:1122:3344:0101::8]:32345"
dataset_kind.type = "crucible"

[[request.dataset]]
zpool_id = "d462a7f7-b628-40fe-80ff-4e4189e2d62b"
address = "[fd00:1122:3344:0101::2]:32221"
dataset_kind.type = "cockroach_db"
dataset_kind.all_addresses = [ "[fd00:1122:3344:0101::2]:32221" ]

# TODO(https://github.com/oxidecomputer/omicron/issues/732): Nexus
# should allocate clickhouse datasets.
[[request.dataset]]
zpool_id = "d462a7f7-b628-40fe-80ff-4e4189e2d62b"
address = "[fd00:1122:3344:0101::5]:8123"
dataset_kind.type = "clickhouse"

[[request.service]]
name = "nexus"
addresses = [ "fd00:1122:3344:0101::3" ]
gz_addresses = []

# TODO(https://github.com/oxidecomputer/omicron/issues/732): Nexus
# should allocate Oximeter services.
[[request.service]]
name = "oximeter"
addresses = [ "fd00:1122:3344:0101::4" ]
gz_addresses = []
