[package]
name = "nexus-external-api"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
dropshot-api-manager-types.workspace = true
dropshot.workspace = true
http.workspace = true
hyper.workspace = true
ipnetwork.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
omicron-workspace-hack.workspace = true
openapiv3.workspace = true
oximeter-types.workspace = true
oxql-types.workspace = true
schemars.workspace = true
scim2-rs.workspace = true
serde.workspace = true
tufaceous-artifact.workspace = true
uuid.workspace = true
