[package]
name = "wicketd-client"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
chrono.workspace = true
installinator-common.workspace = true
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
omicron-workspace-hack.workspace = true
progenitor.workspace = true
regress.workspace = true
reqwest = { workspace = true, features = ["rustls-tls", "stream"] }
schemars.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sled-agent-types.workspace = true
sled-hardware-types.workspace = true
slog.workspace = true
update-engine.workspace = true
uuid.workspace = true
wicket-common.workspace = true
