[package]
name = "wicketd-api"
version = "0.1.0"
edition.workspace = true

[lints]
workspace = true

[dependencies]
bootstrap-agent-client.workspace = true
dropshot.workspace = true
gateway-client.workspace = true
omicron-common.workspace = true
omicron-passwords.workspace = true
omicron-uuid-kinds.workspace = true
omicron-workspace-hack.workspace = true
schemars.workspace = true
semver.workspace = true
serde.workspace = true
sled-hardware-types.workspace = true
slog.workspace = true
tufaceous-artifact.workspace = true
wicket-common.workspace = true
