[package]
name = "omicron-repo-depot-standalone"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
buf-list.workspace = true
bytes.workspace = true
camino.workspace = true
clap.workspace = true
dropshot.workspace = true
futures.workspace = true
libc.workspace = true
oxide-tokio-rt.workspace = true
repo-depot-api.workspace = true
serde_json.workspace = true
signal-hook-tokio.workspace = true
slog.workspace = true
slog-error-chain.workspace = true
tokio = { workspace = true, features = [ "full" ] }
tokio-util.workspace = true
tufaceous-artifact.workspace = true
update-common.workspace = true
omicron-workspace-hack.workspace = true

[[bin]]
name = "repo-depot-standalone"
path = "src/main.rs"
