[package]
name = "key-manager"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
async-trait.workspace = true
camino.workspace = true
hkdf = "0.12.3"
secrecy.workspace = true
sha3.workspace = true
sled-hardware.workspace = true
zeroize.workspace = true

