[package]
name = "key-manager"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
hkdf.workspace = true
omicron-common.workspace = true
secrecy.workspace = true
sha3.workspace = true
slog.workspace = true
thiserror.workspace = true
tokio.workspace = true
zeroize.workspace = true
omicron-workspace-hack.workspace = true

