[package]
name = "helios-tokamak"
description = "Utilities to create a fake Helios system"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
camino.workspace = true
clap.workspace = true
cfg-if.workspace = true
futures.workspace = true
helios-fusion.workspace = true
itertools.workspace = true
ipnetwork.workspace = true
libc.workspace = true
omicron-common.workspace = true
petgraph.workspace = true
rustyline.workspace = true
schemars.workspace = true
serde.workspace = true
shlex.workspace = true
slog.workspace = true
slog-async.workspace = true
slog-term.workspace = true
smf.workspace = true
thiserror.workspace = true
tokio.workspace = true
uuid.workspace = true
zone.workspace = true

[dev-dependencies]
omicron-test-utils.workspace = true
