[package]
name = "oxlog"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
chrono.workspace = true
clap.workspace = true
glob.workspace = true
jiff.workspace = true
rayon.workspace = true
sigpipe.workspace = true
uuid.workspace = true
omicron-workspace-hack.workspace = true

[[bin]]
name = "oxlog"
