# This file contains settings for `cargo hakari`.
# See https://docs.rs/cargo-hakari/latest/cargo_hakari/config for a full list of options.

hakari-package = "omicron-workspace-hack"

# Format for `workspace-hack = ...` lines in other Cargo.tomls. Requires cargo-hakari 0.9.8 or above.
dep-format-version = "4"

# Output lines as `omicron-workspace-hack.workspace = true`. Requires
# cargo-hakari 0.9.28 or above.
workspace-hack-line-style = "workspace-dotted"

# Setting workspace.resolver = "2" in the root Cargo.toml is HIGHLY recommended.
# Hakari works much better with the new feature resolver.
# For more about the new feature resolver, see:
# https://blog.rust-lang.org/2021/03/25/Rust-1.51.0.html#cargos-new-feature-resolver
resolver = "2"

# Add triples corresponding to platforms commonly used by developers here.
# https://doc.rust-lang.org/rustc/platform-support.html
platforms = [
    "x86_64-unknown-linux-gnu",
    "x86_64-apple-darwin",
    "aarch64-apple-darwin",
    "x86_64-unknown-illumos",
    # "x86_64-pc-windows-msvc",
]

# Write out exact versions rather than a semver range. (Defaults to false.)
exact-versions = true

# Use final-excludes rather than traversal-excludes because we'd like to unify
# features across builds performed by rust-analyzer (with `--workspace`) and
# those performed on the command line (without `--workspace`).
[final-excludes]
workspace-members = [
    # Exclude dev-tools-common and xtask because they need to be built quickly.
    "dev-tools-common",
    "xtask",
    
    # Exclude omicron-uuid-kinds because it is a no-std crate. Depending on the
    # workspace-hack isn't too problematic because other projects pulling in
    # omicron as a git dependency will only see an empty workspace-hack. But
    # let's make this explicit.
    "omicron-uuid-kinds",
]
