[package]
name = "tqdb"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
colored.workspace = true
daft.workspace = true
iddqd.workspace = true
omicron-repl-utils.workspace = true
reedline.workspace = true
reconfigurator-cli.workspace = true
serde_json.workspace = true
slog.workspace = true
tabled.workspace = true
trust-quorum-protocol = { workspace = true, features = ["danger_partial_eq_ct_wrapper"] }
trust-quorum-test-utils.workspace = true

omicron-workspace-hack.workspace = true

[[bin]]
name = "tqdb"
path = "src/bin/tqdb/main.rs"
