#
# Oxide API: example configuration file
#

# Maximum number of host phase2 trampoline images we're willing to cache. Note
# that this value is specified in terms of _number of images_, not bytes, and
# our cache is in-memory. We expect this value to be small in production,
# potentially even 1 (i.e., only keep the most-recently-uploaded image).
host_phase2_recovery_image_cache_max_images = 1

[dropshot]
default_request_body_max_bytes = 1048576

[switch]
# For tests, bind to port 0 (i.e., OS chooses an open port) instead of MGS's
# default port for SP communication. This option should be omitted in the real
# config.
udp_listen_port = 0

# Which interface is connected to our local sidecar SP (i.e., the SP that acts
# as our contact to the ignition controller)?
local_ignition_controller_interface = "fake-switch0"

[switch.rpc_retry_config]
# When sending non-reset UDP RPC packets to an SP, how many total attempts do we
# make before giving up?
max_attempts_general = 3

# When sending UDP RPC packets to an SP to reset it, how many total attempts do
# we make before giving up?
max_attempts_reset = 10

# sleep time between UDP RPC resends (up to `max_attempts_*`)
per_attempt_timeout_millis = 1000

[switch.location]
# possible locations where MGS could be running; these names appear in logs and
# are used in the remainder of the `[switch.*]` configuration to define port
# mappings
names = ["switch0", "switch1"]

# `[[switch.location.determination]]` is a list of switch ports we should
# contact in order to determine our location; each port defines a subset of
# `[switch.location.names]` which are the possible location(s) of this MGS
# instance if the message was received on the given SP port. When MGS starts, it
# will send a discovery message on each port listed in this section, collect the
# responses, and determine its location via the intersection of the names listed
# below (for all ports which returned a successful response). This process can
# fail if too few SPs respond (leaving us with 2 or more possible locations) or
# if there is a miscabling that results in an unsolvable system (e.g.,
# determination 0 reports "switch0" and determination 1 reports "switch1").
[[switch.location.determination]]
interfaces = ["fake-sled0", "fake-sled1"]
sp_port_1 = ["switch0"]
sp_port_2 = ["switch1"]

# `[[switch.port.*]]` defines the local data link address (in RFD 250 terms, the
# interface configured to use VLAN tag  assigned to the given port) and the
# logical ID of the remote SP ("sled 7", "switch 1", etc.), which must have an
# entry for each member of `[switch.location]` above.
#
# TODO This section has some concessions to local testing: ultimately we will
# use a single multicast address, target port, and source port, but for now all
# three are configured on a per-port basis, which allows a single system to
# simulate a full set of ports and SPs.
[[switch.port]]
kind = "simulated"
fake-interface = "fake-switch0"
addr = "[::1]:0"
ereport-addr = "[::1]:0"
ignition-target = 0
location = { switch0 = ["switch", 0], switch1 = ["switch", 1] }

[[switch.port]]
kind = "simulated"
fake-interface = "fake-switch1"
addr = "[::1]:0"
ereport-addr = "[::1]:0"
ignition-target = 1
location = { switch0 = ["switch", 1], switch1 = ["switch", 0] }

[[switch.port]]
kind = "simulated"
fake-interface = "fake-sled0"
addr = "[::1]:0"
ereport-addr = "[::1]:0"
ignition-target = 2
location = { switch0 = ["sled", 0], switch1 = ["sled", 0] }

[[switch.port]]
kind = "simulated"
fake-interface = "fake-sled1"
addr = "[::1]:0"
ereport-addr = "[::1]:0"
ignition-target = 3
location = { switch0 = ["sled", 1], switch1 = ["sled", 1] }

#
# Configuration for SP sensor metrics polling
#
[metrics]
# Allow the Oximeter metrics endpoint to bind on the loopback IP. This is
# useful in local testing and development, when the gateway service is not
# given a "real" underlay network IP.
dev_bind_loopback = true

#
# NOTE: for the test suite, if mode = "file", the file path MUST be the sentinel
# string "UNUSED".  The actual path will be generated by the test suite for each
# test.
#
[log]
level = "trace"
mode = "file"
if_exists = "fail"
path = "UNUSED"
