#
# SP simulator: example config file
#

#
# NOTE: for the test suite, all ports MUST be 0 (in order to bind to any
# available port) because the test suite will be running many servers
# concurrently.
#
[[simulated_sps.sidecar]]
multicast_addr = "::1"
bind_addrs = ["[::1]:0", "[::1]:0"]
serial_number = "SimSidecar0"
manufacturing_root_cert_seed = "01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de"
device_id_cert_seed = "01de000000000000000000000000000000000000000000000000000000000000"

[[simulated_sps.sidecar.components]]
id = "dev-0"
device = "fake-tmp-sensor"
description = "FAKE temperature sensor 1"
capabilities = 0x2
presence = "Present"
sensors = [
    {name = "Southwest", kind = "Temperature", sensor_id = 0, last_data.value = 41.7890625, last_data.timestamp = 1234 },
]

[[simulated_sps.sidecar.components]]
id = "dev-1"
device = "fake-tmp-sensor"
description = "FAKE temperature sensor 2"
capabilities = 0x2
presence = "Failed"
sensors = [
    { name = "South", kind = "Temperature", sensor_id = 1, last_error.value = "DeviceError", last_error.timestamp = 1234 },
]

[[simulated_sps.sidecar]]
multicast_addr = "::1"
bind_addrs = ["[::1]:0", "[::1]:0"]
serial_number = "SimSidecar1"
manufacturing_root_cert_seed = "01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de"
device_id_cert_seed = "01de000000000000000000000000000000000000000000000000000000000001"

[[simulated_sps.gimlet]]
multicast_addr = "::1"
bind_addrs = ["[::1]:0", "[::1]:0"]
serial_number = "SimGimlet00"
manufacturing_root_cert_seed = "01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de"
device_id_cert_seed = "01de000000000000000000000000000000000000000000000000000000000002"

[[simulated_sps.gimlet.components]]
id = "sp3-host-cpu"
device = "sp3-host-cpu"
description = "FAKE host cpu"
capabilities = 0
presence = "Present"
serial_console = "[::1]:0"

[[simulated_sps.gimlet.components]]
id = "dev-0"
device = "fake-tmp-sensor"
description = "FAKE temperature sensor"
capabilities = 0x2
presence = "Failed"
sensors = [
    { name = "Southwest", kind = "Temperature", sensor_id = 0, last_error.value = "DeviceError", last_error.timestamp = 1234 },
]
[[simulated_sps.gimlet.components]]
id = "dev-1"
device = "tmp117"
description = "FAKE temperature sensor"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "South", kind = "Temperature", sensor_id = 1, last_data.value = 42.5625, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-2"
device = "tmp117"
description = "FAKE Southeast temperature sensor"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "Southeast", kind = "Temperature", sensor_id = 2, last_data.value = 41.570313, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-6"
device = "at24csw080"
description = "FAKE U.2 Sharkfin A VPD"
capabilities = 0x0
presence = "Present"

[[simulated_sps.gimlet.components]]
id = "dev-7"
device = "max5970"
description = "FAKE U.2 Sharkfin A hot swap controller"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "V12_U2A_A0", kind = "Current", sensor_id = 3, last_data.value = 0.45898438, last_data.timestamp = 1234 },
    { name = "V3P3_U2A_A0", kind = "Current", sensor_id = 4, last_data.value = 0.024414063, last_data.timestamp = 1234 },
    { name = "V12_U2A_A0", kind = "Voltage", sensor_id = 5, last_data.value = 12.03125, last_data.timestamp = 1234 },
    { name = "V3P3_U2A_A0", kind = "Voltage", sensor_id = 6, last_data.value = 3.328125, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-8"
device = "nvme_bmc"
description = "FAKE U.2 A NVMe Basic Management Command"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "U2_N0", kind = "Temperature", sensor_id = 7, last_data.value = 56.0, last_data.timestamp = 1234 },
]
[[simulated_sps.gimlet.components]]
id = "dev-39"
device = "tmp451"
description = "FAKE T6 temperature sensor"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "t6", kind = "Temperature", sensor_id = 9, last_data.value = 70.625, last_data.timestamp = 1234 },
]
[[simulated_sps.gimlet.components]]
id = "dev-53"
device = "max31790"
description = "FAKE Fan controller"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "Southeast", kind = "Speed", sensor_id = 10, last_data.value = 2607.0, last_data.timestamp = 1234 },
    { name = "Northeast", kind = "Speed", sensor_id = 11, last_data.value = 2476.0, last_data.timestamp = 1234 },
    { name = "South", kind = "Speed", sensor_id = 12, last_data.value = 2553.0, last_data.timestamp = 1234 },
    { name = "North", kind = "Speed", sensor_id = 13, last_data.value = 2265.0, last_data.timestamp = 1234 },
    { name = "Southwest", kind = "Speed", sensor_id = 14, last_data.value = 2649.0, last_data.timestamp = 1234 },
    { name = "Northwest", kind = "Speed", sensor_id = 15, last_data.value = 2275.0, last_data.timestamp = 1234 },
]


[[simulated_sps.gimlet]]
multicast_addr = "::1"
bind_addrs = ["[::1]:0", "[::1]:0"]
serial_number = "SimGimlet01"
manufacturing_root_cert_seed = "01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de01de"
device_id_cert_seed = "01de000000000000000000000000000000000000000000000000000000000003"

[[simulated_sps.gimlet.components]]
id = "sp3-host-cpu"
device = "sp3-host-cpu"
description = "FAKE host cpu"
capabilities = 0
presence = "Present"
serial_console = "[::1]:0"


[[simulated_sps.gimlet.components]]
id = "sp3-host-cpu"
device = "sp3-host-cpu"
description = "FAKE host cpu"
capabilities = 0
presence = "Present"
# serial_console = "[::1]:0"

[[simulated_sps.gimlet.components]]
id = "dev-0"
device = "tmp117"
description = "FAKE temperature sensor"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "Southwest", kind = "Temperature", sensor_id = 0, last_data.value = 41.3629, last_data.timestamp = 1234 },
]
[[simulated_sps.gimlet.components]]
id = "dev-1"
device = "tmp117"
description = "FAKE temperature sensor"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "South", kind = "Temperature", sensor_id = 1, last_data.value = 42.5625, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-2"
device = "tmp117"
description = "FAKE Southeast temperature sensor"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "Southeast", kind = "Temperature", sensor_id = 2, last_data.value = 41.570313, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-6"
device = "at24csw080"
description = "FAKE U.2 Sharkfin A VPD"
capabilities = 0x0
presence = "Present"

[[simulated_sps.gimlet.components]]
id = "dev-7"
device = "max5970"
description = "FAKE U.2 Sharkfin A hot swap controller"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "V12_U2A_A0", kind = "Current", sensor_id = 3, last_data.value = 0.41893438, last_data.timestamp = 1234 },
    { name = "V3P3_U2A_A0", kind = "Current", sensor_id = 4, last_data.value = 0.025614603, last_data.timestamp = 1234 },
    { name = "V12_U2A_A0", kind = "Voltage", sensor_id = 5, last_data.value = 12.02914, last_data.timestamp = 1234 },
    { name = "V3P3_U2A_A0", kind = "Voltage", sensor_id = 6, last_data.value = 3.2618, last_data.timestamp = 1234 },
]

[[simulated_sps.gimlet.components]]
id = "dev-8"
device = "nvme_bmc"
description = "FAKE U.2 A NVMe Basic Management Command"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "U2_N0", kind = "Temperature", sensor_id = 7, last_data.value = 56.0, last_data.timestamp = 1234 },
]
[[simulated_sps.gimlet.components]]
id = "dev-39"
device = "tmp451"
description = "FAKE T6 temperature sensor"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "t6", kind = "Temperature", sensor_id = 9, last_data.value = 70.625, last_data.timestamp = 1234 },
]
[[simulated_sps.gimlet.components]]
id = "dev-53"
device = "max31790"
description = "FAKE Fan controller"
capabilities = 0x2
presence = "Present"
sensors = [
    { name = "Southeast", kind = "Speed", sensor_id = 10, last_data.value = 2510.0, last_data.timestamp = 1234 },
    { name = "Northeast", kind = "Speed", sensor_id = 11, last_data.value = 2390.0, last_data.timestamp = 1234 },
    { name = "South", kind = "Speed", sensor_id = 12, last_data.value = 2467.0, last_data.timestamp = 1234 },
    { name = "North", kind = "Speed", sensor_id = 13, last_data.value = 2195.0, last_data.timestamp = 1234 },
    { name = "Southwest", kind = "Speed", sensor_id = 14, last_data.value = 2680.0, last_data.timestamp = 1234 },
    { name = "Northwest", kind = "Speed", sensor_id = 15, last_data.value = 2212.0, last_data.timestamp = 1234 },
]


#
# NOTE: for the test suite, the [log] section is ignored; sp-sim logs are rolled
# into the gateway logfile.
#
[log]
level = "debug"
mode = "stderr-terminal"
