[package]
name = "oximeter-schema"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
chrono.workspace = true
clap.workspace = true
heck.workspace = true
omicron-workspace-hack.workspace = true
oximeter-types.workspace = true
prettyplease.workspace = true
proc-macro2.workspace = true
quote.workspace = true
schemars.workspace = true
serde.workspace = true
slog-error-chain.workspace = true
syn.workspace = true
toml.workspace = true
