[package]
name = "sled-hardware-types"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
daft.workspace = true
illumos-utils.workspace = true
omicron-common.workspace = true
schemars.workspace = true
serde.workspace = true
slog.workspace = true
thiserror.workspace = true
omicron-workspace-hack.workspace = true
test-strategy = { workspace = true, optional = true }
proptest = { workspace = true, optional = true }

[dev-dependencies]
macaddr.workspace = true
proptest.workspace = true
test-strategy.workspace = true

[features]
testing = ["test-strategy", "proptest"]
