[package]
name = "omicron-reconfigurator-exec-unsafe"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[build-dependencies]
omicron-rpaths.workspace = true

[dependencies]
anyhow.workspace = true
camino.workspace = true
clap.workspace = true
dropshot.workspace = true
internal-dns-resolver.workspace = true
internal-dns-types.workspace = true
nexus-db-model.workspace = true
nexus-db-queries.workspace = true
nexus-reconfigurator-execution.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
oxide-tokio-rt.workspace = true
# See omicron-rpaths for more about the "pq-sys" dependency.
pq-sys = "*"
qorb.workspace = true
repo-depot-client.workspace = true
serde_json.workspace = true
slog.workspace = true
supports-color.workspace = true
tokio = { workspace = true, features = [ "full" ] }
update-engine.workspace = true
uuid.workspace = true
omicron-workspace-hack.workspace = true

[[bin]]
name = "reconfigurator-exec-unsafe"
path = "src/main.rs"
