[package]
name = "nexus-db-model"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[build-dependencies.omicron-rpaths]
path = "../../rpaths"

[dependencies]
anyhow = "1.0"
chrono = { version = "0.4", features = ["serde"] }
diesel = { version = "2.0.2", features = ["postgres", "r2d2", "chrono", "serde_json", "network-address", "uuid"] }
hex = "0.4.3"
ipnetwork = "0.20"
macaddr = { version = "1.0.1", features = [ "serde_std" ]}
newtype_derive = "0.1.6"
parse-display = "0.6.0"
# See omicron-rpaths for more about the "pq-sys" dependency.
pq-sys = "*"
rand = "0.8.5"
ref-cast = "1.0"
schemars = { version = "0.8.10", features = ["chrono", "uuid1"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.2.1", features = ["serde", "v4"] }

steno = { git = "https://github.com/oxidecomputer/steno", branch = "node-access" }

db-macros = { path = "../db-macros" }
omicron-common = { path = "../../common" }
nexus-defaults = { path = "../defaults" }
nexus-passwords = { path = "../passwords" }
nexus-types = { path = "../types" }
sled-agent-client = { path = "../../sled-agent-client" }
