[package]
name = "trust-quorum-test-utils"
version = "0.1.0"
edition = "2024"

[lints]
workspace = true

[dependencies]
bootstore.workspace = true
camino.workspace = true
daft.workspace = true
dropshot.workspace = true
gfss = { workspace = true, features = ["danger_partial_eq_ct_wrapper"] }
iddqd.workspace = true
omicron-uuid-kinds.workspace = true
secrecy.workspace = true
serde.workspace = true
serde_json.workspace = true
sled-hardware-types.workspace = true
slog.workspace = true
trust-quorum-protocol = { workspace = true, features = ["danger_partial_eq_ct_wrapper", "testing"] }

omicron-workspace-hack.workspace = true
