[package]
name = "omicron-ddm-admin-client"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
either.workspace = true
progenitor-client.workspace = true
reqwest = { workspace = true, features = ["json", "stream", "rustls-tls"] }
serde.workspace = true
slog.workspace = true
thiserror.workspace = true
tokio.workspace = true
omicron-common.workspace = true
sled-hardware-types.workspace = true
omicron-workspace-hack.workspace = true
ddm-admin-client.workspace = true
uuid.workspace = true

[build-dependencies]
anyhow.workspace = true
omicron-zone-package.workspace = true
progenitor.workspace = true
quote.workspace = true
rustfmt-wrapper.workspace = true
serde_json.workspace = true
toml.workspace = true
