[package]
name = "omicron-ddm-admin-client"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
either.workspace = true
oxnet.workspace = true
progenitor-client.workspace = true
reqwest = { workspace = true, features = ["json", "stream", "rustls-tls"] }
serde.workspace = true
slog.workspace = true
thiserror.workspace = true
tokio.workspace = true
omicron-common.workspace = true
sled-hardware-types.workspace = true
omicron-workspace-hack.workspace = true
ddm-admin-client.workspace = true
uuid.workspace = true
