[package]
name = "gateway-client"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
base64.workspace = true
chrono.workspace = true
daft.workspace = true
gateway-messages.workspace = true
gateway-types.workspace = true
omicron-uuid-kinds.workspace = true
progenitor.workspace = true
rand.workspace = true
reqwest = { workspace = true, features = ["rustls-tls", "stream"] }
serde.workspace = true
serde_json.workspace = true
schemars.workspace = true
slog.workspace = true
thiserror.workspace = true
uuid.workspace = true
omicron-workspace-hack.workspace = true
