[package]
name = "authz-macros"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lib]
proc-macro = true

[lints]
workspace = true

[dependencies]
heck.workspace = true
nexus-macros-common.workspace = true
proc-macro2.workspace = true
quote.workspace = true
serde.workspace = true
serde_tokenstream.workspace = true
syn.workspace = true
omicron-workspace-hack.workspace = true

[dev-dependencies]
expectorate.workspace = true
prettyplease.workspace = true
