[package]
name = "clickhouse-admin-test-utils"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
camino.workspace = true
clickhouse-admin-types.workspace = true
clickward.workspace = true
dropshot.workspace = true
thiserror.workspace = true

omicron-workspace-hack.workspace = true

[dev-dependencies]
camino-tempfile.workspace = true