[package]
name = "trust-quorum-types-versions"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
daft.workspace = true
derive_more.workspace = true
gfss.workspace = true
iddqd.workspace = true
omicron-uuid-kinds.workspace = true
omicron-workspace-hack.workspace = true
rand = { workspace = true, features = ["os_rng"] }
schemars.workspace = true
serde_human_bytes.workspace = true
serde.workspace = true
serde_with = { workspace = true, features = ["hex", "schemars_0_8"] }
sled-hardware-types.workspace = true
slog.workspace = true
slog-error-chain.workspace = true
thiserror.workspace = true

[features]
testing = []
