format_version = 1

[target]
name = "switch_port_control_data_link"
description = "Network data for datalinks related to a switch and management control data"
authz_scope = "fleet"

versions = [
    { version = 1, fields = [ "kind", "link_name", "model", "network", "rack_id", "sled_id", "sled_model", "sled_revision", "sled_serial", "switch_id", "switch_model", "switch_revision", "switch_serial", "switch_slot", "asic_fab", "asic_lot", "asic_wafer", "asic_wafer_loc_x", "asic_wafer_loc_y" ] },
]

[fields.kind]
type = "string"
description = "The kind or class of the data link (examples: physical-device, gateway, switch-port)"

[fields.link_name]
type = "string"
description = "Name of the data link in the system (examples: oxControlService1, opte0, tfport0)"

[fields.model]
type = "string"
description = "Model type of the link, indicating what implements or enables the link itself (examples: TF2, tfportd, STM32H753, opte)"

[fields.network]
type = "string"
description = "Network type of the link (examples: primary-data, management, vpc)"

[fields.rack_id]
type = "uuid"
description = "ID for the link's rack"

[fields.sled_id]
type = "uuid"
description = "ID for the link's sled"

[fields.sled_model]
type = "string"
description = "Model number of the link's sled"

[fields.sled_revision]
type = "u32"
description = "Revision number of the sled"

[fields.sled_serial]
type = "string"
description = "Serial number of the sled"

[fields.switch_id]
type = "uuid"
description = "ID of the switch the link is on"

[fields.switch_model]
type = "string"
description = "Model number of the switch the link is on"

[fields.switch_revision]
type = "u32"
description = "Revision number of the switch the link is on"

[fields.switch_serial]
type = "string"
description = "Serial number of the switch the link is on"

[fields.switch_slot]
type = "u16"
description = "Slot number of the switch the link is on"

[fields.asic_fab]
type = "string"
description = "Fabrication plant identifier of the switch ASIC the link is on"

[fields.asic_lot]
type = "string"
description = "Lot identifier of the switch ASIC the link is on"

[fields.asic_wafer]
type = "u8"
description = "Wafer identifier of the switch ASIC the link is on"

[fields.asic_wafer_loc_x]
type = "i16"
description = "X-coordinate wafer location of the switch ASIC the link is on"

[fields.asic_wafer_loc_y]
type = "i16"
description = "Y-coordinate wafer location of the switch ASIC the link is on"

[[metrics]]
name = "bytes_sent"
description = "Number of bytes sent on the link"
units = "bytes"
datum_type = "cumulative_u64"
versions = [
    { added_in = 1, fields = [] }
]

[[metrics]]
name = "bytes_received"
description = "Number of bytes received on the link"
units = "bytes"
datum_type = "cumulative_u64"
versions = [
    { added_in = 1, fields = [] }
]

[[metrics]]
name = "packets_sent"
description = "Number of packets sent on the link"
units = "count"
datum_type = "cumulative_u64"
versions = [
    { added_in = 1, fields = [] }
]

[[metrics]]
name = "packets_received"
description = "Number of packets received on the link"
units = "count"
datum_type = "cumulative_u64"
versions = [
    { added_in = 1, fields = [] }
]

[[metrics]]
name = "errors_sent"
description = "Number of errors encountered when sending on the link"
units = "count"
datum_type = "cumulative_u64"
versions = [
    { added_in = 1, fields = [] }
]

[[metrics]]
name = "errors_received"
description = "Number of errors encountered when receiving on the link"
units = "count"
datum_type = "cumulative_u64"
versions = [
    { added_in = 1, fields = [] }
]
