[package]
name = "oximeter-instruments"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
chrono = { version = "0.4", features = [ "serde" ] }
dropshot = { git = "https://github.com/oxidecomputer/dropshot", branch = "main", features = [ "usdt-probes" ] }
futures = "0.3.23"
oximeter = { path = "../oximeter" }
http = { version = "0.2.7", optional = true }
uuid = { version = "1.1.0", features = [ "v4", "serde" ] }

[features]
default = ["http-instruments"]
http-instruments = ["http"]
