[package]
name = "oximeter-instruments"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[dependencies]
chrono.workspace = true
dropshot.workspace = true
futures.workspace = true
oximeter.workspace = true
tokio.workspace = true
http = { workspace = true, optional = true }
uuid.workspace = true
omicron-workspace-hack.workspace = true

[features]
default = ["http-instruments"]
http-instruments = ["http"]
