[package]
name = "wicket"
version = "0.1.0"
edition = "2021"

[dependencies]
crossterm = { version = "0.25.0", features = ["event-stream"] }
tui = "0.19.0"
tokio = { version = "1.21.1", features = ["full"] }
anyhow = "1.0.66"
slog = { version = "2.7.0", features = [ "max_level_trace", "release_max_level_debug" ] }
slog-term = "2.9.0"
slog-async = "2.7.0"
futures = "0.3.24"

[[bin]]
name = "wicket"
doc = false
