[package]
name = "wicket"
description = "Technician port TUI"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"
default-run = "wicket"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
buf-list.workspace = true
camino.workspace = true
ciborium.workspace = true
clap.workspace = true
crossterm.workspace = true
futures.workspace = true
hex.workspace = true
humantime.workspace = true
indexmap.workspace = true
indicatif.workspace = true
itertools.workspace = true
omicron-common.workspace = true
owo-colors.workspace = true
ratatui.workspace = true
reqwest.workspace = true
rpassword.workspace = true
serde.workspace = true
serde_json.workspace = true
shell-words.workspace = true
sled-hardware-types.workspace = true
slog.workspace = true
slog-async.workspace = true
slog-envlogger.workspace = true
slog-term.workspace = true
supports-color.workspace = true
textwrap.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true
toml.workspace = true
toml_edit.workspace = true
transceiver-controller.workspace = true
tui-tree-widget.workspace = true
unicode-width.workspace = true
zeroize.workspace = true

omicron-passwords.workspace = true
update-engine.workspace = true
wicket-common.workspace = true
wicketd-client.workspace = true
omicron-workspace-hack.workspace = true
semver.workspace = true
tufaceous-artifact.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
expectorate.workspace = true
maplit.workspace = true
tempfile.workspace = true
proptest.workspace = true

[[bin]]
name = "wicket"
doc = false
