[package]
name = "wicket"
description = "Technician port TUI"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
default-run = "wicket"

[dependencies]
anyhow.workspace = true
buf-list.workspace = true
camino.workspace = true
ciborium.workspace = true
clap.workspace = true
crossterm.workspace = true
futures.workspace = true
hex = { workspace = true, features = ["serde"] }
humantime.workspace = true
indexmap.workspace = true
itertools.workspace = true
omicron-common.workspace = true
once_cell.workspace = true
reqwest.workspace = true
semver.workspace = true
serde.workspace = true
serde_json.workspace = true
sha3.workspace = true
shell-words.workspace = true
slog.workspace = true
slog-async.workspace = true
slog-envlogger.workspace = true
slog-term.workspace = true
snafu.workspace = true
libsw.workspace = true
tar.workspace = true
textwrap.workspace = true
tokio = { workspace = true, features = ["full"] }
tokio-util.workspace = true
toml.workspace = true
toml_edit.workspace = true
tui.workspace = true
tui-tree-widget = "0.12.0"
unicode-width.workspace = true

update-engine.workspace = true
wicket-common.workspace = true
wicketd-client.workspace = true

[dev-dependencies]
assert_cmd.workspace = true
tempfile.workspace = true
proptest.workspace = true

[[bin]]
name = "wicket"
doc = false
