[package]
name = "omicron-pins"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[dependencies]
anyhow.workspace = true
camino.workspace = true
cargo_metadata.workspace = true
fs-err.workspace = true
omicron-workspace-hack.workspace = true
serde.workspace = true
toml_edit.workspace = true

[lints]
workspace = true
