[package]
name = "sled-agent-config-reconciler"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
camino.workspace = true
camino-tempfile.workspace = true
chrono.workspace = true
derive_more.workspace = true
dropshot.workspace = true
glob.workspace = true
id-map.workspace = true
illumos-utils.workspace = true
key-manager.workspace = true
nexus-sled-agent-shared.workspace = true
omicron-common.workspace = true
omicron-uuid-kinds.workspace = true
sled-agent-api.workspace = true
sled-agent-types.workspace = true
sled-hardware.workspace = true
sled-storage.workspace = true
slog.workspace = true
slog-error-chain.workspace = true
thiserror.workspace = true
tokio.workspace = true
tufaceous-artifact.workspace = true
zone.workspace = true

[dev-dependencies]
omicron-test-utils.workspace = true

[features]
testing = []
