[package]
name = "nexus-test-interface"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[build-dependencies]
omicron-rpaths.workspace = true

[dependencies]
async-trait.workspace = true
nexus-config.workspace = true
nexus-db-queries.workspace = true
nexus-sled-agent-shared.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
# See omicron-rpaths for more about the "pq-sys" dependency.
pq-sys = "*"
slog.workspace = true
tokio.workspace = true
uuid.workspace = true
omicron-workspace-hack.workspace = true
omicron-uuid-kinds.workspace = true
