[package]
name = "nexus-test-interface"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
async-trait.workspace = true
nexus-config.workspace = true
nexus-types.workspace = true
omicron-common.workspace = true
omicron-common-extended.workspace = true
slog.workspace = true
uuid.workspace = true
omicron-workspace-hack.workspace = true
