[package]
name = "nexus-fm"
version = "0.1.0"
edition = "2021"

[lints]
workspace = true

[dependencies]
nexus-types.workspace = true
chrono.workspace = true
omicron-uuid-kinds.workspace = true

omicron-workspace-hack.workspace = true
