[package]
name = "nexus-background-task-interface"
version = "0.1.0"
edition.workspace = true
license = "MPL-2.0"

[lints]
workspace = true

[dependencies]
omicron-workspace-hack.workspace = true
thiserror.workspace = true
tokio.workspace = true
