[package]
name = "tufaceous-lib"
version = "0.1.0"
edition = "2021"
license = "MPL-2.0"
publish = false

[lints]
workspace = true

[dependencies]
anyhow = { workspace = true, features = ["backtrace"] }
async-trait.workspace = true
buf-list.workspace = true
bytes.workspace = true
camino.workspace = true
camino-tempfile.workspace = true
chrono.workspace = true
debug-ignore.workspace = true
flate2.workspace = true
fs-err.workspace = true
futures.workspace = true
hex.workspace = true
hubtools.workspace = true
itertools.workspace = true
omicron-common.workspace = true
parse-size.workspace = true
rand.workspace = true
ring = { workspace = true, features = ["std"] }
serde.workspace = true
serde_json.workspace = true
serde_path_to_error.workspace = true
sha2.workspace = true
slog.workspace = true
tar.workspace = true
tokio.workspace = true
toml.workspace = true
tough.workspace = true
url.workspace = true
zip.workspace = true
omicron-workspace-hack.workspace = true

[dev-dependencies]
omicron-test-utils.workspace = true
tokio = { workspace = true, features = ["test-util"] }
